name: Deploy Azure Function App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_FUNCTIONAPP_NAME: Fun-AzureCost-Testv3  # change if different
      PYTHON_VERSION: '3.11'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target .python_packages/lib/site-packages

      - name: Archive build
        run: |
          zip -r functionapp.zip . -x '*.git*'
        shell: bash

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: functionapp.zip
          respect-funcignore: true
          scm-do-build-during-deployment: true

      - name: Post-deploy sync triggers
        run: |
          az functionapp sync-function-triggers --name $AZURE_FUNCTIONAPP_NAME --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}

      - name: Output URL
        run: |
          echo "Deployed: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net"

# Required GitHub Secrets:
# AZURE_CREDENTIALS -> JSON from `az ad sp create-for-rbac --name <name> --role Contributor --scopes /subscriptions/<subId> --sdk-auth`
# AZURE_RESOURCE_GROUP -> Name of the resource group containing the Function App
# (Optional) AZURE_SUBSCRIPTION_ID if not embedded in AZURE_CREDENTIALS