name: Deploy Azure Function App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_FUNCTIONAPP_NAME: Fun-AzureCost-Testv3  # change if different
      PYTHON_VERSION: '3.11'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target .python_packages/lib/site-packages

      - name: Archive build
        run: |
          zip -r functionapp.zip . -x '*.git*'
        shell: bash

      # Deploy using publish profile (ZipDeploy). This avoids storage key restrictions.
      - name: Deploy Function App (Publish Profile)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: functionapp.zip
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          respect-funcignore: true

      - name: Post-deploy sync triggers
        run: |
          az functionapp sync-function-triggers --name $AZURE_FUNCTIONAPP_NAME --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}

      - name: Output URL
        run: |
          echo "Deployed: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net"

# Required GitHub Secrets:
# AZURE_PUBLISH_PROFILE -> Full XML content of the publish profile (ZipDeploy or MSDeploy)
# AZURE_RESOURCE_GROUP   -> Name of the resource group containing the Function App (used for trigger sync)
# (Optional) If you prefer service principal instead, restore azure/login step with AZURE_CREDENTIALS.